In [105]:
# import
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.colors as colors
import datetime as dt
import numpy as np
import random
from ipywidgets import interact, interact_manual
import ipywidgets as widgets
from IPython import display
import time
from pathlib import Path
import pandas as pd
import os
import copy
import networkx as nx
import pickle
import sys
from collections import Counter
from scipy import stats
%matplotlib inline

# change directory

os.chdir("/home/kyoko/Develop/ActualCausation/MABE/MABE_contents/actual_agency")

# import packages -- pyphi

from pyanimats import *
from pyTPM import *
import actual_agency as agency
import pyphi
from pyphi import actual, config, Direction

pyphi.config.VALIDATE_SUBSYSTEM_STATES = False
pyphi.config.PARTITION_TYPE = 'TRI'

# Change directory back to Example directory, now in MABE_contents
os.chdir("../Experiments/analysis_now")

%load_ext autoreload
%autoreload 2
%aimport pyTPM, pyanimats, actual_agency

# omajinai to plotting
plt.style.use('ggplot') 
font = {'family' : 'meiryo'}
matplotlib.rc('font', **font)

# make an array
datas = np.zeros(3000).reshape(250, 12)

prearr = np.sort(np.tile(np.arange(1,11), (1,5))).reshape(50, 1) 
runarr = np.tile(prearr.copy(), (5,1)) #Runs
hidarr = np.sort(np.tile(np.arange(2,7), (1,50))).reshape(250, 1) #Hidden nodes
stsarr = np.tile(np.arange(1,6), (1,50)).reshape(250, 1)

datas[:,0:1] = hidarr
datas[:,1:2] = runarr
datas[:,2:3] = stsarr

# defining some parameters to use 
generations = 30000
n_agents = int(generations/500.+1)
n_runs = 10
n_trials = 64
n_data = 5

agent = 60 # saved generation
trial = 60 # 0~63
run = 1 # 0 ~ n_runs-1 change only this


# Get Line-of-descent (LOD) data from MABE output
    
LOD_data = ['190822_7156331_h2_LOD_data.pkl','190822_7156331_h3_LOD_data.pkl','190822_7156331_h4_LOD_data.pkl','190822_7156331_h5_LOD_data.pkl','190822_7156331_h6_LOD_data.pkl']
LODs = []    
for i in range(len(LOD_data)):
    with open(LOD_data[i],'rb') as f:
        LODs.append(pickle.load(f))

# Get genome data
all_genomes = ['190822_7156331_h2_genome.pkl','190822_7156331_h3_genome.pkl','190822_7156331_h4_genome.pkl','190822_7156331_h5_genome.pkl','190822_7156331_h6_genome.pkl']
genomes = []
for i in range(len(all_genomes)):
    with open(all_genomes[i],'rb') as f:
        genomes.append(pickle.load(f))


# Get activity data
all_activity = ['190822_7156331_h2_activity.pkl','190822_7156331_h3_activity.pkl','190822_7156331_h4_activity.pkl','190822_7156331_h5_activity.pkl','190822_7156331_h6_activity.pkl']
activities = []
for i in range(len(all_activity)):
    with open(all_activity[i],'rb') as f:
        activities.append(pickle.load(f))


# Define functions to find states
# find the most frequent state


def counting3(data):
    c = Counter(data)
    freq_scores = c.most_common()
    if len(freq_scores) < 3:
        return(freq_scores)
    else:
        third_count = freq_scores[2][1]
    
        modes = [freq_scores[0][:], freq_scores[1][:]]
        for p in range(2,len(freq_scores)): #出現回数を比較、追加
            if freq_scores[p][1] == third_count and p < 5:
                modes.append(freq_scores[p])
        return(modes)

# change num(10) to bin(2)
def int2binary(n,node_n):
    holi = [int(x) for x in bin(n)[2:].zfill(node_n)]
    holi.reverse()
    return holi

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [2]:
def num2state(num,n_nodes):
 
    number = '{0:0' + str(n_nodes) + 'b}'
    state = number.format(num)
    state = [int(i) for i in state]

    # returns the state
    return state

In [3]:
# brain acivity, genome, TPM, TPM_gates, cm
genome = []
TPM, TPM_gates, cm = [],[],[]
n_connection = np.zeros(n_data*n_runs)
brain_activity = []

for data in range(n_data):
    n_hnodes = data+2
    for n in range(n_runs):
        place = 5*data + n
        
        # culculate brain activity
        ##brain_activity.append(agency.getBrainActivity(activities[data][n],n_agents=n_agents, n_nodes=n_hnodes+4, n_hidden=n_hnodes))
        #actarr = brain_activity[place][agent][trial]


Creating activity matrix from MABE output...
Creating activity matrix from MABE output...
Creating activity matrix from MABE output...
Creating activity matrix from MABE output...
Creating activity matrix from MABE output...
Creating activity matrix from MABE output...
Creating activity matrix from MABE output...
Creating activity matrix from MABE output...
Creating activity matrix from MABE output...
Creating activity matrix from MABE output...
Creating activity matrix from MABE output...
Creating activity matrix from MABE output...
Creating activity matrix from MABE output...
Creating activity matrix from MABE output...
Creating activity matrix from MABE output...
Creating activity matrix from MABE output...
Creating activity matrix from MABE output...
Creating activity matrix from MABE output...
Creating activity matrix from MABE output...
Creating activity matrix from MABE output...
Creating activity matrix from MABE output...
Creating activity matrix from MABE output...
Creating a

In [4]:

for data in range(n_data):
    n_hnodes = data+2
    for n in range(n_runs):
        place = 5*data + n
        genome.append(agency.get_genome(genomes[data], n, agent))
#print(len(genome[4]))

        a, b, c = genome2TPM(genome[place], n_nodes=n_hnodes+4, n_sensors=2, n_motors=2, gate_type='deterministic',states_convention='loli',remove_sensor_motor_effects=True)
        TPM.append(a)
        TPM_gates.append(b)
        cm.append(c) # right?
        

In [5]:
prestate = np.array([[[36, 16, 4], [20,56], [36,8], [0,16,48,40], [32,0,36], [40,56,14,41],[52,12],[5,24,12], [0,20], [0,52]],
[[112,0,56,24], [0,24,18,70], [84,44,68], [60,12,120,72,121],[32,52,60], [53,100,48,112,40], [48,49,97,107,72], [44,4],[84,108], [32,8,40]],
 [[184,92,93,235,191], [216,92,217,125,111], [212,76,92,196], [32,8,2], [144,146,145,129,163], [172,228,236], [236,220,8,79,204], [212, 96],[44,80,96], [4]],
 [[16,272,388], [192,456,462,198], [376,371,370], [24,8,168,68], [36], [404,220,144], [100], [0,328,288,228], [21,28,72], [12,296,280]],
 [[516], [164,416,484], [608,628,540,520], [708,136], [560,561,563,547,610], [556,564,812], [156,664,728], [80,372,244,116,16], [256,272,464], [244, 112, 372]]])

In [207]:
# 今後しばしばstateがいくつあるかを使うので。

nstate = np.zeros_like(prestate)
for i in range(len(nstate)):
    for j in range(len(nstate[i])):
        nstate[i,j] += len(prestate[i,j])
nstate

array([[3, 2, 2, 4, 3, 4, 2, 3, 2, 2],
       [4, 4, 3, 5, 3, 5, 5, 2, 2, 3],
       [5, 5, 4, 3, 5, 3, 5, 2, 3, 1],
       [3, 4, 3, 4, 1, 3, 1, 4, 3, 3],
       [1, 3, 4, 2, 5, 3, 3, 5, 3, 3]], dtype=object)

In [208]:
state = []
for i in range(len(prestate)):
    for j in range(len(nstate[i])):
        for k in range(nstate[i,j]):
            state.append(np.array(num2state(prestate[i][j][k], 6+i)))
state = np.array(state)
state

array([array([1, 0, 0, 1, 0, 0]), array([0, 1, 0, 0, 0, 0]),
       array([0, 0, 0, 1, 0, 0]), array([0, 1, 0, 1, 0, 0]),
       array([1, 1, 1, 0, 0, 0]), array([1, 0, 0, 1, 0, 0]),
       array([0, 0, 1, 0, 0, 0]), array([0, 0, 0, 0, 0, 0]),
       array([0, 1, 0, 0, 0, 0]), array([1, 1, 0, 0, 0, 0]),
       array([1, 0, 1, 0, 0, 0]), array([1, 0, 0, 0, 0, 0]),
       array([0, 0, 0, 0, 0, 0]), array([1, 0, 0, 1, 0, 0]),
       array([1, 0, 1, 0, 0, 0]), array([1, 1, 1, 0, 0, 0]),
       array([0, 0, 1, 1, 1, 0]), array([1, 0, 1, 0, 0, 1]),
       array([1, 1, 0, 1, 0, 0]), array([0, 0, 1, 1, 0, 0]),
       array([0, 0, 0, 1, 0, 1]), array([0, 1, 1, 0, 0, 0]),
       array([0, 0, 1, 1, 0, 0]), array([0, 0, 0, 0, 0, 0]),
       array([0, 1, 0, 1, 0, 0]), array([0, 0, 0, 0, 0, 0]),
       array([1, 1, 0, 1, 0, 0]), array([1, 1, 1, 0, 0, 0, 0]),
       array([0, 0, 0, 0, 0, 0, 0]), array([0, 1, 1, 1, 0, 0, 0]),
       array([0, 0, 1, 1, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0]),
       ar

In [27]:
cm = np.array(cm)
for i in range(50):
    print(pyphi.connectivity.is_strong(cm[i][4:,4:]))

False
False
False
True
False
True
True
True
False
False
False
False
False
False
True
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
True
False
False


In [209]:
#complexes = pyphi.compute.network.possible_complexes(network, sta)

In [ ]:
comps =list(complexes)
comps

In [45]:
# compute major complexes and 

num_connected = []
MC = []
count = 0

for i in range(50):
    network = pyphi.network.Network(TPM[i],cm[i])
    #sta = tuple(cm[i][0,:].astype(int))
    row = int(i/10)
    cul = i%10
    #print(row, cul)
    for j in range(len(prestate[row][cul])):
        print(state[count+j])
        MC.append(pyphi.compute.network.major_complex(network,state[count+j]))
        num_connected.append(len(list(pyphi.compute.network.possible_complexes(network, state[count+j]))))
    count = count+j+1 
    #print(j, count)

Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

0 0
[1 0 0 1 0 0]
[0 1 0 0 0 0]
[0 0 0 1 0 0]
2 3
0 1
[0 1 0 1 0 0]
[1 1 1 0 0 0]
1 5
0 2
[1 0 0 1 0 0]
[0 0 1 0 0 0]
1 7
0 3
[0 0 0 0 0 0]



Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[0 1 0 0 0 0]



Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[1 1 0 0 0 0]



Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[1 0 1 0 0 0]



Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

3 11
0 4
[1 0 0 0 0 0]
[0 0 0 0 0 0]
[1 0 0 1 0 0]
2 14
0 5
[1 0 1 0 0 0]



                                                         
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[1 1 1 0 0 0]



                                                         
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[0 0 1 1 1 0]



                                                         
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[1 0 1 0 0 1]



                                                         
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

3 18
0 6
[1 1 0 1 0 0]



                                                         
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[0 0 1 1 0 0]



                                                         
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

1 20
0 7
[0 0 0 1 0 1]



Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[0 1 1 0 0 0]



Computing concepts:  67%|██████▋   | 2/3 [00:00<00:00, 18.88it/s]
                                                                 
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[0 0 1 1 0 0]



Finding complexes:   0%|          | 0/1 [00:00<?, ?it/s]        

2 23
0 8
[0 0 0 0 0 0]
[0 1 0 1 0 0]
1 25
0 9
[0 0 0 0 0 0]
[1 1 0 1 0 0]
1 27
1 0
[1 1 1 0 0 0 0]
[0 0 0 0 0 0 0]
[0 1 1 1 0 0 0]
[0 0 1 1 0 0 0]
3 31
1 1
[0 0 0 0 0 0 0]
[0 0 1 1 0 0 0]
[0 0 1 0 0 1 0]
[1 0 0 0 1 1 0]
3 35
1 2
[1 0 1 0 1 0 0]


Computing concepts:   0%|          | 0/7 [00:00<?, ?it/s]

[0 1 0 1 1 0 0]
[1 0 0 0 1 0 0]
2 38
1 3
[0 1 1 1 1 0 0]
[0 0 0 1 1 0 0]
[1 1 1 1 0 0 0]
[1 0 0 1 0 0 0]
[1 1 1 1 0 0 1]
4 43
1 4
[0 1 0 0 0 0 0]



Computing concepts:  29%|██▊       | 2/7 [00:00<00:00, 19.61it/s]
                                                                 
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]
                                                         
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]
                                                         
Computing concepts:   0%|          | 0/7 [00:00<?, ?it/s]

[0 1 1 0 1 0 0]



Computing concepts:  43%|████▎     | 3/7 [00:00<00:00, 28.37it/s]
                                                                 
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]
                                                         
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]
                                                         
Computing concepts:   0%|          | 0/7 [00:00<?, ?it/s]

[0 1 1 1 1 0 0]



Computing concepts:  14%|█▍        | 1/7 [00:00<00:00,  9.60it/s]
                                                                 
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]
                                                         
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]
                                                         
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

2 46
1 5
[0 1 1 0 1 0 1]



                                                         
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[1 1 0 0 1 0 0]



                                                         
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[0 1 1 0 0 0 0]



                                                         
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[1 1 1 0 0 0 0]



Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  9.59it/s]
                                                                 
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[0 1 0 1 0 0 0]



                                                         
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

4 51
1 6
[0 1 1 0 0 0 0]
[0 1 1 0 0 0 1]
[1 1 0 0 0 0 1]
[1 1 0 1 0 1 1]
[1 0 0 1 0 0 0]
4 56
1 7
[0 1 0 1 1 0 0]
[0 0 0 0 1 0 0]
1 58
1 8
[1 0 1 0 1 0 0]



                                                         
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[1 1 0 1 1 0 0]



Computing concepts: 100%|██████████| 3/3 [00:00<00:00, 29.88it/s]
                                                                 
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

1 60
1 9
[0 1 0 0 0 0 0]
[0 0 0 1 0 0 0]
[0 1 0 1 0 0 0]
2 63
2 0
[1 0 1 1 1 0 0 0]



Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[0 1 0 1 1 1 0 0]



Computing concepts: 100%|██████████| 3/3 [00:00<00:00, 27.96it/s]
                                                                 
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[0 1 0 1 1 1 0 1]



Computing concepts: 100%|██████████| 3/3 [00:00<00:00, 28.68it/s]
                                                                 
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[1 1 1 0 1 0 1 1]



Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[1 0 1 1 1 1 1 1]



Computing concepts: 100%|██████████| 3/3 [00:00<00:00, 28.91it/s]


4 68
2 1
[1 1 0 1 1 0 0 0]
[0 1 0 1 1 1 0 0]
[1 1 0 1 1 0 0 1]
[0 1 1 1 1 1 0 1]
[0 1 1 0 1 1 1 1]
4 73
2 2
[1 1 0 1 0 1 0 0]
[0 1 0 0 1 1 0 0]
[0 1 0 1 1 1 0 0]
[1 1 0 0 0 1 0 0]
3 77
2 3
[0 0 1 0 0 0 0 0]
[0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 1 0]
2 80
2 4
[1 0 0 1 0 0 0 0]


Computing concepts:   0%|          | 0/7 [00:00<?, ?it/s]

[1 0 0 1 0 0 1 0]
[1 0 0 1 0 0 0 1]
[1 0 0 0 0 0 0 1]
[1 0 1 0 0 0 1 1]
4 85
2 5
[1 0 1 0 1 1 0 0]



Computing concepts:  14%|█▍        | 1/7 [00:00<00:00,  9.51it/s]
                                                                 
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]
                                                         
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]
                                                         
Computing concepts: 100%|██████████| 3/3 [00:00<00:00, 28.53it/s]
                                                                 
Computing concepts:   0%|          | 0/7 [00:00<?, ?it/s]

[1 1 1 0 0 1 0 0]



Computing concepts:  14%|█▍        | 1/7 [00:00<00:00,  9.60it/s]
                                                                 
Computing concepts: 100%|██████████| 3/3 [00:00<00:00, 29.13it/s]
                                                                 
Computing concepts:   0%|          | 0/7 [00:00<?, ?it/s]

[1 1 1 0 1 1 0 0]



Computing concepts:  14%|█▍        | 1/7 [00:00<00:00,  9.31it/s]
                                                                 
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

2 88
2 6
[1 1 1 0 1 1 0 0]
[1 1 0 1 1 1 0 0]
[0 0 0 0 1 0 0 0]
[0 1 0 0 1 1 1 1]
[1 1 0 0 1 1 0 0]
4 93
2 7
[1 1 0 1 0 1 0 0]



Computing concepts: 100%|██████████| 3/3 [00:00<00:00, 28.08it/s]
                                                                 
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[0 1 1 0 0 0 0 0]



Computing concepts: 100%|██████████| 3/3 [00:00<00:00, 28.01it/s]
                                                                 
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

1 95
2 8
[0 0 1 0 1 1 0 0]
[0 1 0 1 0 0 0 0]
[0 1 1 0 0 0 0 0]
2 98
2 9
[0 0 0 0 0 1 0 0]
0 99
3 0
[0 0 0 0 1 0 0 0 0]



Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  9.20it/s]
                                                                 
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[1 0 0 0 1 0 0 0 0]



Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  9.37it/s]
                                                                 
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[1 1 0 0 0 0 1 0 0]



Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  9.90it/s]
                                                                 
Computing concepts:   0%|          | 0/15 [00:00<?, ?it/s]

2 102
3 1
[0 1 1 0 0 0 0 0 0]



Computing concepts:  93%|█████████▎| 14/15 [00:00<00:00, 14.77it/s]
                                                                   
Computing concepts: 100%|██████████| 7/7 [00:00<00:00, 11.35it/s]
                                                                 
Computing concepts: 100%|██████████| 7/7 [00:00<00:00, 10.92it/s]
                                                                 
Computing concepts: 100%|██████████| 7/7 [00:00<00:00, 11.83it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  9.27it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  9.79it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  9.10it/s]
                                                                 
Computing concepts:   0%|          | 0/15 [00:00<?, ?it/s]

[1 1 1 0 0 1 0 0 0]



Computing concepts:  93%|█████████▎| 14/15 [00:00<00:00, 12.67it/s]
                                                                   
Computing concepts:  14%|█▍        | 1/7 [00:00<00:00,  8.71it/s]
                                                                 
Computing concepts:  14%|█▍        | 1/7 [00:00<00:00,  7.39it/s]
                                                                 
Computing concepts:  14%|█▍        | 1/7 [00:00<00:00,  8.41it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  8.89it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  8.95it/s]
                                                                 
Computing concepts:   0%|          | 0/15 [00:00<?, ?it/s]

[1 1 1 0 0 1 1 1 0]



Computing concepts:  93%|█████████▎| 14/15 [00:00<00:00, 12.59it/s]
                                                                   
Computing concepts: 100%|██████████| 7/7 [00:00<00:00, 11.20it/s]
                                                                 
Computing concepts:  14%|█▍        | 1/7 [00:00<00:00,  8.15it/s]
                                                                 
Computing concepts:  14%|█▍        | 1/7 [00:00<00:00,  7.87it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  8.22it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  8.75it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  8.88it/s]
                                                                 
Computing concepts:   0%|          | 0/15 [00:00<?, ?it/s]

[0 1 1 0 0 0 1 1 0]



Computing concepts: 100%|██████████| 15/15 [00:00<00:00, 12.60it/s]
                                                                   
Computing concepts:  14%|█▍        | 1/7 [00:00<00:00,  7.77it/s]
                                                                 
Computing concepts:  14%|█▍        | 1/7 [00:00<00:00,  7.84it/s]
                                                                 
Computing concepts:  14%|█▍        | 1/7 [00:00<00:00,  8.24it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  7.19it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  6.57it/s]
                                                                 
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

3 106
3 2
[1 0 1 1 1 1 0 0 0]



Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  8.55it/s]
                                                                 
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[1 0 1 1 1 0 0 1 1]



Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  8.97it/s]
                                                                 
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[1 0 1 1 1 0 0 1 0]



Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  8.79it/s]
                                                                 
Computing concepts:   0%|          | 0/15 [00:00<?, ?it/s]

2 109
3 3
[0 0 0 0 1 1 0 0 0]



Computing concepts:  73%|███████▎  | 11/15 [00:00<00:00, 12.22it/s]
                                                                   
Computing concepts:  14%|█▍        | 1/7 [00:00<00:00,  7.54it/s]
                                                                 
Computing concepts:  14%|█▍        | 1/7 [00:00<00:00,  8.12it/s]
                                                                 
Computing concepts: 100%|██████████| 7/7 [00:00<00:00, 10.26it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  8.43it/s]
                                                                 
Computing concepts:   0%|          | 0/15 [00:00<?, ?it/s]

[0 0 0 0 0 1 0 0 0]



Computing concepts:  93%|█████████▎| 14/15 [00:00<00:00, 15.43it/s]
                                                                   
Computing concepts:  86%|████████▌ | 6/7 [00:00<00:00, 10.81it/s]
                                                                 
Computing concepts:  14%|█▍        | 1/7 [00:00<00:00,  8.09it/s]
                                                                 
Computing concepts:  14%|█▍        | 1/7 [00:00<00:00,  7.90it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  8.87it/s]
                                                                 
Computing concepts:   0%|          | 0/15 [00:00<?, ?it/s]

[0 1 0 1 0 1 0 0 0]



Computing concepts:  93%|█████████▎| 14/15 [00:00<00:00, 16.70it/s]
                                                                   
Computing concepts: 100%|██████████| 7/7 [00:00<00:00, 12.03it/s]
                                                                 
Computing concepts:  14%|█▍        | 1/7 [00:00<00:00,  7.60it/s]
                                                                 
Computing concepts: 100%|██████████| 7/7 [00:00<00:00, 12.18it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  8.86it/s]
                                                                 
Computing concepts:   0%|          | 0/15 [00:00<?, ?it/s]

[0 0 1 0 0 0 1 0 0]



Computing concepts: 100%|██████████| 15/15 [00:00<00:00, 16.65it/s]
                                                                   
Computing concepts:  14%|█▍        | 1/7 [00:00<00:00,  7.59it/s]
                                                                 
Computing concepts: 100%|██████████| 7/7 [00:00<00:00, 10.20it/s]
                                                                 
Computing concepts:  14%|█▍        | 1/7 [00:00<00:00,  8.21it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  9.36it/s]
                                                                 
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

3 113
3 4
[0 0 0 1 0 0 1 0 0]
0 114
3 5
[1 1 0 0 1 0 1 0 0]



Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[0 1 1 0 1 1 1 0 0]



Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[0 1 0 0 1 0 0 0 0]



Finding complexes:   0%|          | 0/7 [00:00<?, ?it/s]         

2 117
3 6
[0 0 1 1 0 0 1 0 0]


Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

0 118
3 7
[0 0 0 0 0 0 0 0 0]



Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  8.76it/s]
                                                                 
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[1 0 1 0 0 1 0 0 0]



Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  8.70it/s]
                                                                 
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[1 0 0 1 0 0 0 0 0]



Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  8.54it/s]
                                                                 
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[0 1 1 1 0 0 1 0 0]



Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  8.68it/s]
                                                                 
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

3 122
3 8
[0 0 0 0 1 0 1 0 1]



Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  7.98it/s]
                                                                 
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[0 0 0 0 1 1 1 0 0]



Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  8.12it/s]
                                                                 
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[0 0 1 0 0 1 0 0 0]



Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  8.15it/s]
                                                                 
Computing concepts:   0%|          | 0/15 [00:00<?, ?it/s]

2 125
3 9
[0 0 0 0 0 1 1 0 0]
[1 0 0 1 0 1 0 0 0]
[1 0 0 0 1 1 0 0 0]
2 128
4 0
[1 0 0 0 0 0 0 1 0 0]



Computing concepts: 100%|██████████| 15/15 [00:00<00:00, 12.87it/s]
                                                                   
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  7.81it/s]
                                                                 
Computing concepts:  86%|████████▌ | 6/7 [00:00<00:00,  7.49it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  7.27it/s]
                                                                 
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

0 129
4 1
[0 0 1 0 1 0 0 1 0 0]



Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  6.16it/s]
                                                                 
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[0 1 1 0 1 0 0 0 0 0]



Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  6.34it/s]
                                                                 
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[0 1 1 1 1 0 0 1 0 0]



Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  6.23it/s]
                                                                 
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

2 132
4 2
[1 0 0 1 1 0 0 0 0 0]



Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[1 0 0 1 1 1 0 1 0 0]



Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[1 0 0 0 0 1 1 1 0 0]



Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[1 0 0 0 0 0 1 0 0 0]



Computing concepts:   0%|          | 0/31 [00:00<?, ?it/s]

3 136
4 3
[1 0 1 1 0 0 0 1 0 0]



Computing concepts: 100%|██████████| 31/31 [00:08<00:00,  1.84it/s]
                                                                   
Computing concepts: 100%|██████████| 15/15 [00:00<00:00, 11.68it/s]
                                                                   
Computing concepts:  93%|█████████▎| 14/15 [00:00<00:00, 12.16it/s]
                                                                   
Computing concepts: 100%|██████████| 15/15 [00:01<00:00,  7.98it/s]
                                                                   
Computing concepts:   0%|          | 0/7 [00:00<?, ?it/s]


Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  7.31it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  7.23it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  7.58it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  6.87it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  6.34it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  6.83it/s]
                                                                 
Computing concepts:  67%|██████▋   | 2/3 [00:00<00:00,  5.13it/s]
                                                                 
Computing concepts:   0%|          | 0/31 [00:00<?, ?it/s]

[0 0 1 0 0 0 1 0 0 0]



Computing concepts: 100%|██████████| 31/31 [00:12<00:00,  1.02it/s]
                                                                   
Computing concepts: 100%|██████████| 15/15 [00:01<00:00,  8.11it/s]
                                                                   
Computing concepts:  93%|█████████▎| 14/15 [00:01<00:00, 10.10it/s]
                                                                   
Computing concepts: 100%|██████████| 15/15 [00:01<00:00,  7.25it/s]
                                                                   
Evaluating Φ cuts:  57%|█████▋    | 8/14 [00:04<00:02,  2.35it/s]


Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  6.67it/s]
                                                                 
Computing concepts:  57%|█████▋    | 4/7 [00:00<00:00,  6.76it/s]
                                                                 
Computing concepts:  86%|████████▌ | 6/7 [00:00<00:00,  6.70it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  6.49it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  5.37it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  6.65it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  5.51it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  5.81it/s]
          

1 138
4 4
[1 0 0 0 1 1 0 0 0 0]



Computing concepts:  93%|█████████▎| 14/15 [00:01<00:00,  9.78it/s]
                                                                   
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  6.52it/s]
                                                                 
Computing concepts: 100%|██████████| 7/7 [00:00<00:00,  6.57it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  6.98it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  6.53it/s]
                                                                 
Computing concepts:   0%|          | 0/15 [00:00<?, ?it/s]

[1 0 0 0 1 1 0 0 0 1]



Computing concepts:  93%|█████████▎| 14/15 [00:01<00:00,  9.11it/s]
                                                                   
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  6.95it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  7.52it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  6.95it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  6.10it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  7.02it/s]
                                                                 
Computing concepts:   0%|          | 0/15 [00:00<?, ?it/s]

[1 0 0 0 1 1 0 0 1 1]



Computing concepts: 100%|██████████| 15/15 [00:01<00:00,  9.96it/s]
                                                                   
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  7.23it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  7.81it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  6.75it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  6.03it/s]
                                                                 
Computing concepts:   0%|          | 0/15 [00:00<?, ?it/s]

[1 0 0 0 1 0 0 0 1 1]



Computing concepts: 100%|██████████| 15/15 [00:01<00:00,  8.89it/s]
                                                                   
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  7.29it/s]
                                                                 
Computing concepts:  86%|████████▌ | 6/7 [00:00<00:00,  7.27it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  7.27it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  6.78it/s]
                                                                 
Computing concepts:   0%|          | 0/15 [00:00<?, ?it/s]

[1 0 0 1 1 0 0 0 1 0]



Computing concepts:  93%|█████████▎| 14/15 [00:00<00:00, 11.55it/s]
                                                                   
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  7.25it/s]
                                                                 
Computing concepts:  43%|████▎     | 3/7 [00:00<00:00,  7.22it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  7.46it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  6.12it/s]
                                                                 
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

4 143
4 5
[1 0 0 0 1 0 1 1 0 0]



Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  6.33it/s]
                                                                 
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[1 0 0 0 1 1 0 1 0 0]



Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  5.92it/s]
                                                                 
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

[1 1 0 0 1 0 1 1 0 0]



Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  5.83it/s]
                                                                 
Computing concepts:   0%|          | 0/31 [00:00<?, ?it/s]

2 146
4 6
[0 0 1 0 0 1 1 1 0 0]



Computing concepts:  94%|█████████▎| 29/31 [00:01<00:00, 22.38it/s]
                                                                   
Computing concepts:  87%|████████▋ | 13/15 [00:00<00:00, 12.09it/s]
                                                                   
Computing concepts:  87%|████████▋ | 13/15 [00:00<00:00, 12.61it/s]
                                                                   
Computing concepts:   0%|          | 0/31 [00:00<?, ?it/s]

[1 0 1 0 0 1 1 0 0 0]



Computing concepts:  97%|█████████▋| 30/31 [00:01<00:00, 23.15it/s]
                                                                   
Computing concepts:  87%|████████▋ | 13/15 [00:00<00:00, 13.15it/s]
                                                                   
Computing concepts:  87%|████████▋ | 13/15 [00:00<00:00, 12.96it/s]
                                                                   
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  7.52it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  6.54it/s]
                                                                 
Computing concepts:   0%|          | 0/31 [00:00<?, ?it/s]

[1 0 1 1 0 1 1 0 0 0]



Computing concepts:  90%|█████████ | 28/31 [00:00<00:00, 22.44it/s]
                                                                   
Computing concepts:  87%|████████▋ | 13/15 [00:00<00:00, 12.18it/s]
                                                                   
Computing concepts:  87%|████████▋ | 13/15 [00:00<00:00, 12.15it/s]
                                                                   
Computing concepts:  86%|████████▌ | 6/7 [00:00<00:00,  7.12it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  6.46it/s]
                                                                 
Computing concepts:   0%|          | 0/63 [00:00<?, ?it/s]

2 149
4 7
[0 0 0 1 0 1 0 0 0 0]



Computing concepts: 100%|██████████| 63/63 [00:10<00:00,  2.82it/s]
                                                                   
Computing concepts:  94%|█████████▎| 29/31 [00:01<00:00, 21.36it/s]
                                                                   
Computing concepts:  16%|█▌        | 5/31 [00:00<00:03,  7.24it/s]


Computing concepts:  97%|█████████▋| 30/31 [00:01<00:00, 16.39it/s]
                                                                   
Computing concepts:  94%|█████████▎| 29/31 [00:01<00:00, 11.01it/s]
                                                                   
Computing concepts:  94%|█████████▎| 29/31 [00:01<00:00, 12.56it/s]
                                                                   
Computing concepts: 100%|██████████| 15/15 [00:00<00:00, 13.67it/s]
                                                                   
Computing concepts: 100%|██████████| 15/15 [00:00<00:00, 14.12it/s]
                                                                   
Computing concepts:  93%|█████████▎| 14/15 [00:00<00:00, 12.99it/s]
                                                                   
Computing concepts:  80%|████████  | 12/15 [00:00<00:00, 10.22it/s]
                                                                   
Evaluating Φ cuts:  71%|███████▏  | 10/14 [00:02

Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  7.14it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  6.75it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  7.71it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  7.08it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  6.48it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  6.43it/s]
                                                                 
Computing concepts:   0%|          | 0/63 [00:00<?, ?it/s]

[0 1 0 1 1 1 0 1 0 0]



Computing concepts: 100%|██████████| 63/63 [00:20<00:00,  1.26it/s]
                                                                   
Computing concepts:  48%|████▊     | 15/31 [00:00<00:01, 14.11it/s]


Computing concepts:  90%|█████████ | 28/31 [00:01<00:00, 21.72it/s]
                                                                   
Computing concepts:  97%|█████████▋| 30/31 [00:02<00:00, 13.09it/s]
                                                                   
Computing concepts:  97%|█████████▋| 30/31 [00:02<00:00, 11.68it/s]
                                                                   
Computing concepts:  97%|█████████▋| 30/31 [00:01<00:00, 14.33it/s]
                                                                   
Computing concepts: 100%|██████████| 15/15 [00:00<00:00, 13.65it/s]
                                                                   
Computing concepts:  93%|█████████▎| 14/15 [00:00<00:00, 11.83it/s]
                                                                   


Computing concepts:  87%|████████▋ | 13/15 [00:00<00:00, 11.98it/s]
                                                                   
Computing concepts: 100%|██████████| 15/15 [00:00<00:00, 13.53it/s]
                                                                   
Computing concepts: 100%|██████████| 15/15 [00:00<00:00, 13.35it/s]
                                                                   
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  7.47it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  7.35it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  7.52it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  7.60it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  7.26it/s

[0 0 1 1 1 1 0 1 0 0]



Computing concepts: 100%|██████████| 63/63 [00:18<00:00,  1.77it/s]
                                                                   
Computing concepts:  71%|███████   | 22/31 [00:00<00:00, 18.63it/s]


Computing concepts:  90%|█████████ | 28/31 [00:01<00:00, 19.72it/s]
                                                                   
Computing concepts:  97%|█████████▋| 30/31 [00:02<00:00, 12.81it/s]
                                                                   
Computing concepts: 100%|██████████| 31/31 [00:02<00:00,  7.12it/s]
                                                                   
Computing concepts:  97%|█████████▋| 30/31 [00:02<00:00, 10.26it/s]
                                                                   
Computing concepts: 100%|██████████| 15/15 [00:00<00:00, 13.50it/s]
                                                                   
Computing concepts:  87%|████████▋ | 13/15 [00:00<00:00, 11.93it/s]
                                                                   
Evaluating Φ cuts:   0%|          | 0/14 [00:00<?, ?it/s]


Computing concepts:  80%|████████  | 12/15 [00:00<00:00, 12.03it/s]
                                                                   
Computing concepts: 100%|██████████| 15/15 [00:00<00:00, 13.36it/s]
                                                                   
Computing concepts:  87%|████████▋ | 13/15 [00:00<00:00, 11.70it/s]
                                                                   
Computing concepts:  86%|████████▌ | 6/7 [00:00<00:00,  7.25it/s]
                                                                 
Computing concepts:  57%|█████▋    | 4/7 [00:00<00:00,  7.32it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  7.33it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  7.27it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  7.17it/s

[0 0 0 1 1 1 0 1 0 0]



Computing concepts: 100%|██████████| 63/63 [00:17<00:00,  1.95it/s]
                                                                   
Computing concepts:  35%|███▌      | 11/31 [00:00<00:01, 11.80it/s]


Computing concepts: 100%|██████████| 31/31 [00:01<00:00, 23.72it/s]
                                                                   
Computing concepts: 100%|██████████| 31/31 [00:02<00:00, 13.00it/s]
                                                                   
Computing concepts: 100%|██████████| 31/31 [00:02<00:00, 10.09it/s]
                                                                   
Computing concepts:  97%|█████████▋| 30/31 [00:01<00:00, 12.43it/s]
                                                                   
Computing concepts:  87%|████████▋ | 13/15 [00:00<00:00, 12.60it/s]
                                                                   
Computing concepts:  47%|████▋     | 7/15 [00:00<00:00,  8.55it/s]


Computing concepts:  87%|████████▋ | 13/15 [00:00<00:00, 12.38it/s]
                                                                   
Computing concepts:  87%|████████▋ | 13/15 [00:00<00:00, 11.41it/s]
                                                                   
Computing concepts:  93%|█████████▎| 14/15 [00:00<00:00, 12.53it/s]
                                                                   
Computing concepts: 100%|██████████| 15/15 [00:00<00:00, 13.40it/s]
                                                                   
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  7.12it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  6.91it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  6.92it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  6.97

[0 0 0 0 0 1 0 0 0 0]



Computing concepts: 100%|██████████| 63/63 [00:11<00:00,  2.50it/s]
                                                                   
Computing concepts:  90%|█████████ | 28/31 [00:01<00:00, 21.84it/s]
                                                                   
Evaluating Φ cuts:  27%|██▋       | 8/30 [00:03<00:12,  1.78it/s]


Computing concepts:  94%|█████████▎| 29/31 [00:01<00:00, 15.85it/s]
                                                                   
Computing concepts: 100%|██████████| 31/31 [00:02<00:00, 12.79it/s]
                                                                   
Computing concepts:  97%|█████████▋| 30/31 [00:01<00:00, 13.78it/s]
                                                                   
Computing concepts: 100%|██████████| 15/15 [00:00<00:00, 12.36it/s]
                                                                   
Computing concepts:  93%|█████████▎| 14/15 [00:00<00:00, 13.49it/s]
                                                                   
Computing concepts:  87%|████████▋ | 13/15 [00:00<00:00, 11.95it/s]
                                                                   
Computing concepts:  73%|███████▎  | 11/15 [00:00<00:00, 11.28it/s]


Computing concepts:  87%|████████▋ | 13/15 [00:00<00:00, 12.57it/s]
                                                                   
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  7.39it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  7.20it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  7.25it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  7.15it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  5.65it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  5.88it/s]
                                                                 
Computing concepts:   0%|          | 0/31 [00:00<?, ?it/s]

4 154
4 8
[0 1 0 0 0 0 0 0 0 0]



Computing concepts: 100%|██████████| 31/31 [00:07<00:00,  2.92it/s]
                                                                   
Computing concepts: 100%|██████████| 15/15 [00:00<00:00, 13.01it/s]
                                                                   
Computing concepts: 100%|██████████| 15/15 [00:01<00:00, 10.12it/s]
                                                                   
Computing concepts:  93%|█████████▎| 14/15 [00:01<00:00,  7.65it/s]
                                                                   
Evaluating Φ cuts: 100%|██████████| 14/14 [00:08<00:00,  1.73it/s]


Computing concepts:  87%|████████▋ | 13/15 [00:00<00:00, 11.76it/s]
                                                                   
Computing concepts:  93%|█████████▎| 14/15 [00:00<00:00, 10.62it/s]
                                                                   
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  6.53it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  6.61it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  7.20it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  6.55it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  6.75it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  6.07it/s]
  

Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  5.70it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  5.68it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  5.59it/s]
                                                                 
Computing concepts:   0%|          | 0/31 [00:00<?, ?it/s]

[0 1 0 0 0 1 0 0 0 0]



Computing concepts:  97%|█████████▋| 30/31 [00:03<00:00,  7.20it/s]
                                                                   
Computing concepts:  93%|█████████▎| 14/15 [00:00<00:00, 12.74it/s]
                                                                   
Computing concepts: 100%|██████████| 15/15 [00:01<00:00, 10.95it/s]
                                                                   
Computing concepts:  93%|█████████▎| 14/15 [00:01<00:00, 10.34it/s]
                                                                   
Computing concepts: 100%|██████████| 15/15 [00:00<00:00, 12.88it/s]
                                                                   
Finding complexes:  16%|█▌        | 5/31 [01:12<07:06, 16.41s/it]


Computing concepts:  87%|████████▋ | 13/15 [00:00<00:00,  8.27it/s]
                                                                   
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  6.80it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  6.58it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  6.41it/s]
                                                                 
Computing concepts:  57%|█████▋    | 4/7 [00:00<00:00,  6.60it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  6.39it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  6.42it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  6.03it/s]
      

[0 1 1 1 0 1 0 0 0 0]



Computing concepts: 100%|██████████| 31/31 [00:04<00:00,  7.02it/s]
                                                                   
Computing concepts: 100%|██████████| 15/15 [00:00<00:00, 13.93it/s]
                                                                   
Computing concepts: 100%|██████████| 15/15 [00:01<00:00, 11.10it/s]
                                                                   
Computing concepts:  87%|████████▋ | 13/15 [00:00<00:00,  8.34it/s]
                                                                   
Computing concepts:  93%|█████████▎| 14/15 [00:00<00:00, 13.42it/s]
                                                                   


Computing concepts:  93%|█████████▎| 14/15 [00:00<00:00, 11.98it/s]
                                                                   
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  6.59it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  6.55it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  6.16it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  6.73it/s]
                                                                 
Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  6.48it/s]
                                                                 
Computing concepts: 100%|██████████| 7/7 [00:00<00:00,  8.52it/s]
                                                                 
Computing concepts: 100%|██████████| 7/7 [00:00<00:00,  8.04it/s]
      

                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  5.75it/s]
                                                                 
Computing concepts:   0%|          | 0/7 [00:00<?, ?it/s]

2 157
4 9
[0 0 1 1 1 1 0 1 0 0]



Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  6.93it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  6.15it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  6.17it/s]
                                                                 
Computing concepts:   0%|          | 0/7 [00:00<?, ?it/s]

[0 0 0 1 1 1 0 0 0 0]



Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  6.46it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  6.51it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  6.48it/s]
                                                                 
Computing concepts:   0%|          | 0/7 [00:00<?, ?it/s]

[0 1 0 1 1 1 0 1 0 0]



Computing concepts:  71%|███████▏  | 5/7 [00:00<00:00,  6.71it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  6.03it/s]
                                                                 
Computing concepts:  33%|███▎      | 1/3 [00:00<00:00,  6.64it/s]
                                                                 
Evaluating Φ cuts:  50%|█████     | 1/2 [00:00<00:00,  2.54it/s]
                                                                

2 160


In [89]:
MC

[┌───────────────────────────────────────┐
 │ System irreducibility analysis: Φ = 0 │
 │ NullCut(())                           │
 │ Subsystem()                           │
 │ ()                                    │
 │ ()                                    │
 │                                       │
 └───────────────────────────────────────┘,
 ┌───────────────────────────────────────┐
 │ System irreducibility analysis: Φ = 0 │
 │ NullCut(())                           │
 │ Subsystem()                           │
 │ ()                                    │
 │ ()                                    │
 │                                       │
 └───────────────────────────────────────┘,
 ┌───────────────────────────────────────┐
 │ System irreducibility analysis: Φ = 0 │
 │ NullCut(())                           │
 │ Subsystem()                           │
 │ ()                                    │
 │ ()                                    │
 │                                       │
 └───────

In [98]:
# make dictionary of data, name, phi etc to make pandas array 

alldicts=[]
counter = 0
data_counter = 0
for d in prestate:
    run_counter = 0
    for r in d:
        state_counter = 0
        for s in range(len(r)):
            newdict = {'data' : data_counter,
                       'run' : run_counter,
                       'state' : s,
                       'Phi' : MC[counter].phi,
                       'Sub': MC[counter].subsystem,
                       'SizeofSub':len(MC[counter].subsystem)
                      }
            alldicts.append(newdict)
            counter+=1
        run_counter+=1
    data_counter+=1

In [103]:
#print(([d for d in alldicts if d['Phi']>0]))
phis = [d for d in alldicts if d['Phi']>0]
phis_sorted_phi = sorted(phis, key=lambda x:x['Phi'], reverse=True)
phis_sorted_data = sorted(phis, key=lambda x:x['data'])
#print(phis_sorted)
print(phis_sorted_data)

[{'data': 0, 'run': 7, 'state': 1, 'Phi': 1.0, 'Sub': Subsystem(n4, n5), 'SizeofSub': 2}, {'data': 1, 'run': 4, 'state': 0, 'Phi': 0.875, 'Sub': Subsystem(n5, n6), 'SizeofSub': 2}, {'data': 1, 'run': 4, 'state': 1, 'Phi': 0.484376, 'Sub': Subsystem(n4, n5, n6), 'SizeofSub': 3}, {'data': 1, 'run': 4, 'state': 2, 'Phi': 0.484376, 'Sub': Subsystem(n4, n5, n6), 'SizeofSub': 3}, {'data': 1, 'run': 5, 'state': 0, 'Phi': 0.687499, 'Sub': Subsystem(n5, n6), 'SizeofSub': 2}, {'data': 1, 'run': 5, 'state': 2, 'Phi': 0.381943, 'Sub': Subsystem(n5, n6), 'SizeofSub': 2}, {'data': 1, 'run': 5, 'state': 4, 'Phi': 0.381943, 'Sub': Subsystem(n5, n6), 'SizeofSub': 2}, {'data': 1, 'run': 8, 'state': 0, 'Phi': 0.381943, 'Sub': Subsystem(n4, n5), 'SizeofSub': 2}, {'data': 1, 'run': 8, 'state': 1, 'Phi': 0.381943, 'Sub': Subsystem(n4, n5), 'SizeofSub': 2}, {'data': 2, 'run': 0, 'state': 1, 'Phi': 1.0, 'Sub': Subsystem(n4, n5), 'SizeofSub': 2}, {'data': 2, 'run': 0, 'state': 2, 'Phi': 1.0, 'Sub': Subsystem(n

In [172]:
#pd.DataFrame.from_dict(phis_sorted_phi)
p_datas = pd.DataFrame.from_dict(phis_sorted_data)

In [162]:
ces

════════════════════════════════════════════════════════════
            Cause-effect structure (3 concepts)             
════════════════════════════════════════════════════════════
  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  
          Concept: Mechanism = [n4], φ = 0.333332           
  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  
              MIC                         MIE               
  ┌──────────────────────────┐┌──────────────────────────┐  
  │  φ = 0.333332            ││  φ = 1/2                 │  
  │  Purview = [n4, n5]      ││  Purview = [n4, n5, n6]  │  
  │  MIP:                    ││  MIP:                    │  
  │     ∅      ∅     n4      ││     ∅       ∅       n4   │  
  │    ─── ✕ ───── ✕ ───     ││    ─── ✕ ──────── ✕ ───  │  
  │     ∅    n4,n5    ∅      ││     ∅    n4,n5,n6    ∅   │  
  │  Repertoire:             ││  Repertoire:             │  
  │    ┌──────────────┐      ││    ┌───────────────┐     │  
  │    │ S     Pr(S)  │ 

In [160]:
ces[2].cause_purview

(4, 5, 6)

In [173]:
# culculate mechanism/purview/concept for every subsystems？

mech_lengths = []
purv_lengths = []
concepts = []

for i in range(len(p_datas)):
    ces = pyphi.compute.subsystem.ces(p_datas['Sub'][i])

    mechanismlength = 0
    purviewlength = 0
    for c in ces:
        mechanismlength += len(c.mechanism)
        purviewlength += len(c.cause_purview)+len(c.effect_purview)
    
    concepts.append(len(ces))
    mech_lengths.append(mechanismlength)
    purv_lengths.append(purviewlength)


In [196]:
# make pandas array to conbine

#p_connects = pd.DataFrame({'nConnects':num_connected})
p_concepts = pd.DataFrame({'nConcepts':concepts})
p_mechs = pd.DataFrame({'nMechs':mech_lengths})
p_purvs = pd.DataFrame({'nPurvs':purv_lengths})

p_s = [p_concepts, p_mechs, p_purvs]

In [202]:
p_datas = p_datas.join(p_s) # 本当にnConnectsは対応している？osiete 表のつくりか

In [ ]:
# culculate average of phi for each data
# to take others in consderation, if there is no mention about data of run, phi is zero

nstate = np.array([[3, 2, 2, 4, 3, 4, 2, 3, 2, 2],
       [4, 4, 3, 5, 3, 5, 5, 2, 2, 3],
       [5, 5, 4, 3, 5, 3, 5, 2, 3, 1],
       [3, 4, 3, 4, 1, 3, 1, 4, 3, 3],
       [1, 3, 4, 2, 5, 3, 3, 5, 3, 3]])

def culAvePhi(dataarr, numdata, statearr):
    numstates = statearr[numdata]
    for i in range(len(numstates)):
        for j in range(numstates[i]):
            

In [221]:
#if p_datas['data'] == '0': #????? osiete どうやって'dataの値がxのときのPhiの値をとるのか
 #   print(p_datas['Phi'])

TypeError: cannot compare a dtyped [int64] array with a scalar of type [bool]

In [212]:
for i in range(nstate[0][0]):
    print('nyan')

nyan
nyan
nyan


In [203]:
p_datas

data  run  state       Phi                        Sub  SizeofSub  \
0      0    7      1  1.000000          Subsystem(n4, n5)          2   
1      1    4      0  0.875000          Subsystem(n5, n6)          2   
2      1    4      1  0.484376      Subsystem(n4, n5, n6)          3   
3      1    4      2  0.484376      Subsystem(n4, n5, n6)          3   
4      1    5      0  0.687499          Subsystem(n5, n6)          2   
5      1    5      2  0.381943          Subsystem(n5, n6)          2   
6      1    5      4  0.381943          Subsystem(n5, n6)          2   
7      1    8      0  0.381943          Subsystem(n4, n5)          2   
8      1    8      1  0.381943          Subsystem(n4, n5)          2   
9      2    0      1  1.000000          Subsystem(n4, n5)          2   
10     2    0      2  1.000000          Subsystem(n4, n5)          2   
11     3    0      2  1.000000          Subsystem(n7, n8)          2   
12     3    1      0  2.812499      Subsystem(n6, n7, n8)          3   
13     3    1      1  0.875000          Subsystem(n6, n7)          2   
14     3    1      2  1.145830          Subsystem(n6, n7)          2   
15     3    1      3  0.583330      Subsystem(n6, n7, n8)          3   
16     3    3      0  0.333333  Subsystem(n4, n6, n7, n8)          4   
17     3    3      1  0.687500          Subsystem(n7, n8)          2   
18     3    3      2  0.472656  Subsystem(n4, n6, n7, n8)          4   
19     3    3      3  0.687500          Subsystem(n7, n8)          2   
20     4    0      0  0.875000          Subsystem(n7, n8)          2   
21     4    3      0  2.812759  Subsystem(n4, n6, n8, n9)          4   
22     4    3      1  1.500000          Subsystem(n4, n6)          2   
23     4    4      0  1.222982  Subsystem(n6, n7, n8, n9)          4   
24     4    4      1  1.000000          Subsystem(n6, n7)          2   
25     4    4      2  1.067010  Subsystem(n6, n7, n8, n9)          4   
26     4    4      3  1.067010  Subsystem(n6, n7, n8, n9)          4   
27     4    4      4  0.884376  Subsystem(n6, n7, n8, n9)          4   
28     4    5      0  0.777776          Subsystem(n8, n9)          2   
29     4    5      1  0.777776          Subsystem(n8, n9)          2   
30     4    5      2  1.500000          Subsystem(n8, n9)          2   
31     4    6      1  1.000000          Subsystem(n6, n8)          2   
32     4    6      2  1.000000          Subsystem(n6, n8)          2   
33     4    7      0  1.000000          Subsystem(n6, n7)          2   
34     4    7      1  1.000000          Subsystem(n6, n7)          2   
35     4    7      2  1.000000          Subsystem(n6, n7)          2   
36     4    7      3  1.000000          Subsystem(n6, n7)          2   
37     4    7      4  1.000000          Subsystem(n6, n7)          2   
38     4    8      0  0.687500          Subsystem(n7, n8)          2   
39     4    8      1  0.421874      Subsystem(n5, n7, n8)          3   
40     4    8      2  0.421874      Subsystem(n5, n7, n8)          3   
41     4    9      0  1.402774          Subsystem(n7, n8)          2   
42     4    9      1  1.083333      Subsystem(n4, n7, n8)          3   
43     4    9      2  0.687500          Subsystem(n4, n8)          2   

    nConcepts  nMechs  nPurvs  
0           2       2       6  
1           2       2       8  
2           3       3      16  
3           3       3      16  
4           2       2       8  
5           2       2       8  
6           2       2       8  
7           2       2       8  
8           2       2       8  
9           2       2       8  
10          2       2       8  
11          2       2       8  
12          4       6      21  
13          2       2       6  
14          3       4      10  
15          3       4      15  
16          4       4      20  
17          2       2       8  
18          4       4      20  
19          2       2       8  
20          2       2       6  
21         10      17      71  
22          2       3      

In [ ]:
num_connected

In [107]:
alldicts

[{'data': 0,
  'run': 0,
  'state': 0,
  'Phi': 0.0,
  'Sub': Subsystem(),
  'SizeofSub': 0},
 {'data': 0,
  'run': 0,
  'state': 1,
  'Phi': 0.0,
  'Sub': Subsystem(),
  'SizeofSub': 0},
 {'data': 0,
  'run': 0,
  'state': 2,
  'Phi': 0.0,
  'Sub': Subsystem(),
  'SizeofSub': 0},
 {'data': 0,
  'run': 1,
  'state': 0,
  'Phi': 0.0,
  'Sub': Subsystem(),
  'SizeofSub': 0},
 {'data': 0,
  'run': 1,
  'state': 1,
  'Phi': 0.0,
  'Sub': Subsystem(),
  'SizeofSub': 0},
 {'data': 0,
  'run': 2,
  'state': 0,
  'Phi': 0.0,
  'Sub': Subsystem(),
  'SizeofSub': 0},
 {'data': 0,
  'run': 2,
  'state': 1,
  'Phi': 0.0,
  'Sub': Subsystem(),
  'SizeofSub': 0},
 {'data': 0,
  'run': 3,
  'state': 0,
  'Phi': 0.0,
  'Sub': Subsystem(),
  'SizeofSub': 0},
 {'data': 0,
  'run': 3,
  'state': 1,
  'Phi': 0.0,
  'Sub': Subsystem(),
  'SizeofSub': 0},
 {'data': 0,
  'run': 3,
  'state': 2,
  'Phi': 0.0,
  'Sub': Subsystem(),
  'SizeofSub': 0},
 {'data': 0,
  'run': 3,
  'state': 3,
  'Phi': 0.0,
  'Sub'

In [106]:
# counter = 0
# for d in prestate:
#     for r in d:
#         for s in range(len(r)):
#             print(counter)
#             counter+=1
            

In [ ]:
# def _test(arr):
#     mode = arr**2
#     return mode

# array = [[3, 14, 1],[2,5,6]]
# test = np.frompyfunc(_test, 1, 1)

# a = test(array)
# a

In [ ]:
# # 一つとってくる
# # 二進数に変換
# # 文字ごとに分割
# # 0で埋める
# # tupleにする？



# def _InttoState(arr, x, y):
#     mode = bin(arr[x,y])[:2]
#     a = list(mode)
#     for i in range():
#         a[i] = int(a[i])
#     return a


# xarr = np.arange(5)
# yarr = np.arange(10)

# InttoState = np.frompyfunc(_InttoState, 3, 1)

# InttoState(state, xarr, yarr)

# # InttoState = np.frompyfunc(_InttoState, 4, 1)
# # InttoState(state,1)

In [ ]:
# arr = 42
# mode = bin(state[0][0][1])[2:]
# a = list(mode)
# for i in range(8):
#     a[i] = int(a[i])
#     if len(a) < 8:
#         a.insert(0,0)
        
# tuple(a)

In [ ]:
# error
# for i in range(5):
#     for j in range(10):
#         for k in range(5):
#             if state[i][j][k:k+1]:
#                 mode = np.array(bin(arr[i][j][k])[:2])
#                 a = list(mode)
#                 for i in range():
#                     a[i] = int(a[i])
#                 else:
#                     break